name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: create multiple branch & push
        run: |
          for i in {1..10}
          do
            branch_name=hoge-$i
            git switch -c $branch_name
            git push origin $branch_name
          done
