name: Remove matched branches

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove branches
        run: |
          git fetch
          target_branches=$(git branch -r | sed "s/origin\///" | grep hoge-)
          echo $target_branches

          current_timestamp=$(date --date '15 days' +%s)
          echo $current_timestamp
          for branch in $target_branches
          do
            branch_timestamp=$(git show -s --format='%ct')
            echo $branch_timestamp

            diff_day=$(( ($current_timestamp - $branch_timestamp) / 24 / 60 / 60))

            echo $diff_day

            if [ $diff_day -gt 14 ]; then
              echo "Delete branch $branch"
              git push origin :$branch
            fi
          done
