name: Remove matched branches

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Remove branches
        run: |
          git fetch
          target_branches=$(git branch -r | sed "s/origin\///" | grep '^\s*companion_')

          current_timestamp=$(date --date '15 days' +%s)
          for branch in $target_branches
          do
            branch_timestamp=$(git show -s --format='%ct')

            diff_day=$(( ($current_timestamp - $branch_timestamp) / 24 / 60 / 60))

            if [ $diff_day -gt 14 ]; then
              echo "Delete branch $branch"
              git push -q origin :$branch
            fi
          done
