name: Remove matched branches

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove branches
        run: |
          git fetch
          branches=$(git branch -r)
          echo $branches
