name: Remove matched branches

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove branches
        shell: bash
        run: |
          git fetch
          target_branches=$(git branch -r | grep '^\s*origin/companion_' || [[ $? == 1 ]])

          current_timestamp=$(date --date '15 days' +%s)
          for branch in $target_branches
          do
            branch_timestamp=$(git show $branch -s --format='%ct')

            diff_day=$(( ($current_timestamp - $branch_timestamp) / 24 / 60 / 60))

            if [ $diff_day -gt 14 ]; then
              delete_target_branch=$(echo $branch | sed "s/origin\///")
              echo "Delete branch $delete_target_branch"
              git push -q origin :$delete_target_branch
            fi
          done
