name: Remove matched branches

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove branches
        run: |
          git fetch
          target_branches=$(git branch -r | grep hoge-)

          current_timestamp=$(date +%s)
          for branch in $target_branches
          do
            branch_timestamp=$(git show -s --format='%ct')
            diff_day=$(expr \($current_timestamp - $branch_timestamp\) / 24 / 60 / 60)

            if [ $diff_day -gt 14 ]; then
              git push origin :$branch
            fi
            git push origin :$branch
          done
