name: Try matrix
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        value: 
          [
            {name: 'aaa', hoge: 'aaa'},
            {name: 'bbb', hoge: 'bbb'},
            {name: 'ccc', hoge: ''}
          ]
    steps:
      - name: prints
        run: echo ${{ matrix.value.name }} ${{ matrix.value.hoge != '' && 'someValue:' || '' }}${{ matrix.value.hoge }}
      
    
